#!/bin/bash
#this script generates a release tarball

version=0.5

subversion="https://www.peapodpy.org.uk/subversion/peapod/tags/peapod-${version}"

#grab a changelog
svn log $subversion > /tmp/CHANGELOG

echo $version

sed 's/xxx/'$version'/' < setup.py > setup.py.version
mv setup.py.version setup.py

#copy docs from website
website=http://www.peapodpy.org/
mkdir docs
links --dump ${website}about > docs/about.txt
links --dump ${website}configuration > docs/configuration.txt
links --dump ${website}dependencies > docs/dependencies.txt
links --dump ${website}downloading-peapod > docs/getting.txt
links --dump ${website}using-peapod > docs/using.txt

python setup.py sdist
mv dist/*.gz /tmp
rm -rf build
rm -rf dist
